stages:
  - deploy

deploy_to_github:
  stage: deploy
  only:
    changes:
      - docs/en/*
  script:
    - export BRANCH=connect-module-docs-$(git show -s --format=%ct $CI_COMMIT_SHA)
    - export USERNAME=MostafaMoradii
    - export TOKEN=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
    - export MODULE=Connect
    - export REPO=https://$USERNAME:$TOKEN@github.com/MostafaMoradii/openclassify-docs.git
    - git clone $REPO
    - cd openclassify-docs
    - git config user.email "mostafa@visiosoft.com.tr"
    - git config user.name "Mostafa Moradi"
    - git checkout -b $BRANCH
    - mkdir -p addons/modules/connect
    - cp ../docs/en/* addons/modules/connect/
    - git add .
    - git commit -m "Add file from GitLab repository"
    - git push origin $BRANCH
