name: Push to Another GitHub Repository
on:
  push:
    paths:
      - 'docs/en/**'

env:
  TARGET_REPO: MostafaMoradii/openclassify-docs
  REPO_DIR: openclassify-docs

jobs:
  deploy_to_github:
    runs-on: ubuntu-latest
    steps:
      - name: Push generated webpage to another repository
        uses: nkoppel/push-files-to-another-repository@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          PAT: ${{ secrets.PAT }}
          USERNAME: ${{ secrets.USERNAME }}
          EMAIL: 'mostafa21tr@gmail.com'
        with:
          destination-branch: 'docs'
          source-files: 'docs/en/'
          destination-username: $USERNAME
          destination-repository: 'MostafaMoradii/openclassify-docs'
          destination-directory: 'addons/modules/connect'
          commit-email: $EMAIL
