name: Push to Another GitHub Repository
on:
  push:
    paths:
      - 'docs/en/**'

env:
  TARGET_REPO: MostafaMoradii/openclassify-docs
  REPO_DIR: openclassify-docs
  TARGET_BRANCH: connect-module-docs-$(date)
  GH_USERNAME: ${{ secrets.USERNAME }}
  GH_TOKEN: ${{ secrets.PAT }}

jobs:
  deploy_to_github:
    runs-on: ubuntu-latest
    steps:
      - name: Push to target repository
        run: |
          echo $TARGET_REPO
          echo $REPO_DIR
          echo $TARGET_BRANCH
          echo $GH_USERNAME
          echo $GH_TOKEN
