name: Push to Another GitHub Repository
on:
  push:
    paths:
      - 'docs/en/**'

env:
  TARGET_REPO: MostafaMoradii/openclassify-docs
  REPO_DIR: openclassify-docs

jobs:
  deploy_to_github:
    runs-on: ubuntu-latest
    steps:
      - name: Push to docs repository
        run: |
          echo "DATETIME=$(date +%s)" >> $GITHUB_ENV
          git clone "https://${{ secrets.USERNAME }}:${{ secrets.PAT }}@github.com/$TARGET_REPO.git"
          cd $REPO_DIR
          git checkout -b docs-$DATETIME
          cp ../docs/en/ addons/modules/connect
          git add .
          git commit -m "Update docs file"
          git push origin docs-$DATETIME
