name: Push to Another GitHub Repository
on:
  push:
    paths:
      - 'docs/en/**'

env:
  TARGET_REPO: MostafaMoradii/openclassify-docs
  REPO_DIR: openclassify-docs

jobs:
  deploy_to_github:
    runs-on: ubuntu-latest
    steps:
      - name: Push generated webpage to another repository
        uses: nkoppel/push-files-to-another-repository
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          source-files: 'docs/en/'
          destination-username: 'MostafaMoradii'
          destination-repository: $TARGET_REPO
          destination-directory: 'addons/modules/connect'
          commit-email: 'mostafa@visiosoft.com.tr'
