name: Push to Another GitHub Repository
on:
  push:
    paths:
      - 'docs/en/**'

env:
  TARGET_REPO: MostafaMoradii/openclassify-docs
  REPO_DIR: openclassify-docs
  TARGET_BRANCH: connect-module-docs-${{ github.event.repository.updated_at }}

jobs:
  deploy_to_github:
    runs-on: ubuntu-latest
    steps:
      - name: Push to docs repository
        run: |
          git clone "https://${{ secrets.USERNAME }}:${{ secrets.PAT }}N@github.com/$TARGET_REPO.git"
          cd $REPO_DIR
          git checkout -b $TARGET_BRANCH
          cp ../docs/en/ addons/modules/connect
          git add .
          git commit -m "Update docs file"
          git push origin $TARGET_BRANCH
