name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          source_file: 'docs/en/**'
          destination_repo: 'MostafaMoradii/openclassify-docs'
          destination_folder: 'addons/modules/connect'
          user_email: 'mostafa21tr@gmail.com'
          user_name: 'MostafaMoradii'
          commit_message: 'A custom message for the commit'