name: Push to Another GitHub Repository
on:
  push:
    paths:
      - 'docs/en/**'

env:
  TARGET_REPO: MostafaMoradii/openclassify-docs
  REPO_DIR: openclassify-docs

jobs:
  deploy_to_github:
    runs-on: ubuntu-latest
    steps:
      - uses: jitterbit/get-changed-files@v1
      - name: Push to docs repository
        run: |
          git clone "https://${{ secrets.USERNAME }}:${{ secrets.PAT }}@github.com/$TARGET_REPO.git"
          echo "${{ steps.abc.outputs.all }}"
